from typing import List, Dict

TAXONOMY_DOMAINS: List[str] = [
    "AI",
    "Generative AI",
    "Machine Learning",
    "Programming",
    "Java",
    "Python",
    "JavaScript",
    "DSA",
    "Software Engineering",
    "Backend",
    "Frontend",
    "Full Stack",
    "APIs",
    "Databases",
    "System Design",
    "Cloud",
    "DevOps",
    "Cybersecurity",
    "Networking",
    "Hardware",
    "Developer Tools",
    "Career",
    "Interview Preparation",
    "Technology News",
    "Gaming",
    "Entertainment",
    "Other"
]

DOMAIN_HIERARCHY: Dict[str, str] = {
    "Java": "Software Engineering",
    "Python": "Programming",
    "JavaScript": "Programming",
    "DSA": "Software Engineering",
    "Backend": "Software Engineering",
    "Frontend": "Software Engineering",
    "Full Stack": "Software Engineering",
    "APIs": "Backend",
    "Databases": "Backend",
    "System Design": "Software Engineering",
    "Cloud": "Cloud",
    "DevOps": "Cloud",
    "Cybersecurity": "Cybersecurity",
    "Networking": "Cybersecurity",
    "Hardware": "Hardware",
    "Developer Tools": "Software Engineering",
    "Interview Preparation": "Career",
    "Generative AI": "AI",
    "Machine Learning": "AI",
    "Gaming": "Gaming",
    "Entertainment": "Entertainment"
}
